export const APP_CONFIGS = [
  {
    id: 'burndown',
    name: 'BurnDown',
    status: 'live',
    tagline: 'Eliminate debt. Fuel your FIRE.',
    description: 'Debt snowball & avalanche calculator with FIRE integration.',
    accentStart: '#FF6B35',
    accentEnd: '#FFB347',
    accentClass: 'fire',
    glowColor: 'rgba(255,107,53,0.14)',
    features: [
      'Snowball & Avalanche strategies side-by-side',
      'FIRE timeline integration with freed cash flow',
      'PDF & Excel export with shareable links',
    ],
    launchLabel: 'Launch BurnDown',
    icon: 'flame',
  },
  {
    id: 'portfolio',
    name: 'Portfolio',
    status: 'coming-soon',
    tagline: 'Grow wealth with clarity.',
    description: 'Investment portfolio tracker with allocation insights.',
    accentStart: '#2DD4BF',
    accentEnd: '#22C55E',
    accentClass: 'teal',
    glowColor: 'rgba(45,212,191,0.14)',
    features: [
      'Multi-asset portfolio allocation views',
      'Rebalancing recommendations',
      'Performance attribution analysis',
    ],
    launchLabel: 'Coming Soon',
    icon: 'trending-up',
  },
  {
    id: 'compound',
    name: 'Compound',
    status: 'coming-soon',
    tagline: 'See your money multiply.',
    description: 'Compound interest & investment growth projections.',
    accentStart: '#8b7cf7',
    accentEnd: '#a78bfa',
    accentClass: 'purple',
    glowColor: 'rgba(139,124,247,0.14)',
    features: [
      'Lump sum & recurring contribution modeling',
      'Inflation-adjusted projections',
      'Side-by-side scenario comparison',
    ],
    launchLabel: 'Coming Soon',
    icon: 'bar-chart',
  },
];
